import{a as v,S as q,i as h}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function p(o,t){const a="https://pixabay.com",n="/api/",e="?key=43339942-99901bbe97dd078ee80d94f6e",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,i=a+n+e+r;return(await v.get(i)).data}const u=document.querySelector(".gallery");function y(o){const t=o.hits.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:m,comments:w,downloads:P})=>`<li class="card-item">
  <a href=${e}>
  <img src=${n} alt="${r}"/>
    <ul class="card-info">
      <li>Likes<p>${i}</p></li>
      <li>Views<p>${m}</p></li>
      <li>Comments<p>${w}</p></li>
      <li>Downloads<p>${P}</p></li>
    </ul>
    </a>
</li>`).join("");u.insertAdjacentHTML("beforeend",t),new q("gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const $=document.querySelector(".img-search-form"),g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let c,s,L;$.addEventListener("submit",M);f.addEventListener("click",O);async function M(o){if(o.preventDefault(),b(),u.innerHTML="",c=o.target.elements.query.value.trim(),s=1,c===""){l("Sorry, there are no search terms entered. Please try again!");return}E();try{const t=await p(c,s);if(L=Math.ceil(t.totalHits/15),t.totalHits===0){d(),l("Sorry, there are no images matching your search query. Please try again!");return}y(t)}catch(t){l(t)}d(),S(),o.target.reset()}async function O(){s+=1,E();try{const t=await p(c,s);y(t)}catch(t){l(t)}d(),S();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function x(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function E(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function l(o){h.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function S(){s>=L?(b(),h.info({message:"We're sorry, but you've reached the end of search results."})):x()}
//# sourceMappingURL=commonHelpers.js.map
